spring:
  datasource:
    url: jdbc:mysql://localhost:3308/demo?useSSL=false&serverTimezone=UTC
    username: bbd
    password: bbd526
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
